// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // Make sure that you have the AGP plugin 8.1+ dependency

    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    id 'com.google.gms.google-services' version '4.4.2' apply false
//
//    // Add the dependency for the Crashlytics Gradle plugin
    id 'com.google.firebase.crashlytics' version '3.0.4' apply false

}

